import sys
import os

# Ensure the local core directory is in the path
# Path: src/agents/implementations/TechnicalArchitect/main.py
# Core target: src/agents/core/
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../core')))
from base_agent import PythonBaseAgent

from features.scaffolding import AgentScaffoldingSkill

class TechnicalArchitect(PythonBaseAgent):
    def __init__(self):
        super().__init__('architect', 'Technical Architect')
        self.scaffolding_skill = AgentScaffoldingSkill(self)

    def execute_task(self, task):
        # DEFENSIVE: Validate task_type
        task_type = task.get('type')
        if not task_type or not isinstance(task_type, str):
            task_type = 'general'
        
        description = task.get('description', '')
        
        if task_type == 'generate_implementation_plan':
            return self.generate_implementation_plan(description)
        elif task_type == 'scaffold_agent':
            return self.scaffolding_skill.execute(task)
        else:
            # Accept any task type - provide architectural guidance
            return {
                'success': True,
                'result': f"Architecture guidance for: {task.get('title', 'Untitled')}",
                'message': f"Architect processed {task_type} task"
            }

    def handle_message(self, message):
        return {'acknowledged': True, 'agent': self.name}

    def generate_implementation_plan(self, roadmap_item):
        self.log(f"Architect: Generating implementation plan for '{roadmap_item}'")
        self.update_status('thinking')
        
        # In a real autonomous swarm, this would call an LLM MCP or internal model
        # For the scaffolding, we provide a structured template
        plan = f"""
# Implementation Plan: {roadmap_item}
Generated by: Technical Architect Agent

## Context
Breaking down Phase 1 foundation task for stabilization.

## Technical Tasks
1. Initialize Database Schema (Prisma/Postgres)
2. Setup Redis for state management
3. Implement inter-agent Messenger service
4. Update BaseAgent to use Messenger

## Required MCPs
- filesystem
- postgres (planned)
- redis (planned)
"""
        self.update_status('idle')
        return {
            'success': True,
            'plan': plan,
            'roadmap_item': roadmap_item
        }

if __name__ == "__main__":
    agent = TechnicalArchitect()
    agent.run()
