#!/bin/bash
# Helper to find where to install Figma plugin

echo "=========================================="
echo "Finding Figma Plugin Installation Menu"
echo "=========================================="
echo ""
echo "The plugin installation location varies by Figma version."
echo "Try these methods in order:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 1: Main Menu (Most Common)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Click the Menu icon (☰) in TOP-LEFT corner"
echo "2. Look for 'Plugins' in the dropdown"
echo "3. Click 'Plugins'"
echo "4. Look for 'Development' or 'Manage plugins...'"
echo "5. Click 'Development' → 'Import plugin from manifest...'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 2: Right-Click Menu"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Right-click on empty canvas area"
echo "2. Look for 'Plugins' in context menu"
echo "3. Click 'Plugins' → 'Development'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 3: Keyboard Shortcut"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Press Ctrl + / (or Cmd + / on Mac)"
echo "2. Type 'plugin' or 'import'"
echo "3. Look for 'Import plugin from manifest'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "METHOD 4: Top Menu Bar"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Look at top menu bar (between Object and Text)"
echo "2. Find 'Plugins' menu"
echo "3. Click 'Plugins' → 'Development'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "IMPORTANT CHECKS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ Are you using Figma DESKTOP? (not browser)"
echo "  → Browser version doesn't support development plugins"
echo ""
echo "✓ Is Figma up to date?"
echo "  → Update from: Menu → Help → Check for updates"
echo ""
echo "✓ Is developer mode enabled?"
echo "  → Some versions require enabling in settings"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PLUGIN FILE LOCATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
MANIFEST="/home/tiago/Repositoty/Agent-Company/claude-talk-to-figma-mcp/src/claude_mcp_plugin/manifest.json"
echo "Manifest file:"
echo "  $MANIFEST"
echo ""
if [ -f "$MANIFEST" ]; then
    echo "✓ File exists and is ready"
else
    echo "✗ File not found!"
fi
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "WHAT TO LOOK FOR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The menu option you're looking for is:"
echo "  'Import plugin from manifest...'"
echo ""
echo "It should:"
echo "  - Open a file picker dialog"
echo "  - Allow you to select .json files"
echo "  - Be under 'Development' or 'Plugins' menu"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Still can't find it? Try:"
echo "  1. Update Figma Desktop to latest version"
echo "  2. Check if you're logged in as admin/owner"
echo "  3. Look in Menu → Help → Plugins"
echo ""

