"""
Professional PDF Generator for Mason Business Model (fpdf2)
Handles tables, formatting, and layout based on Osterwalder's Canvas.
"""
from fpdf import FPDF
import re

# Paths - updated for D: drive
md_path = r"D:\.gemini\antigravity\brain\f391020b-58e9-4e7f-bc45-68440a54f470\mason_business_model.md"
pdf_path = r"D:\Projetos\Agent-Company\mason_business_model_canvas.pdf"

class OsterwalderPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_title("Mason Manage - Business Model Canvas")
        self.set_author("Strategy Agent")

    def header(self):
        if self.page_no() > 1:
            self.set_font('Helvetica', 'I', 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, 'Mason Manage - Business Model Canvas', 0, 0, 'R')
            self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def cover_page(self):
        self.add_page()
        self.set_font('Helvetica', 'B', 24)
        self.set_text_color(26, 26, 46)
        self.ln(60)
        self.cell(0, 20, 'Mason Manage', 0, 1, 'C')
        self.set_font('Helvetica', '', 18)
        self.set_text_color(245, 158, 11)
        self.cell(0, 15, 'Business Model Canvas', 0, 1, 'C')
        self.ln(10)
        self.set_font('Helvetica', 'I', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'Created using the Osterwalder Methodology', 0, 1, 'C')
        self.ln(80)
        self.set_font('Helvetica', '', 10)
        self.cell(0, 10, 'Generated by Strategy Agent', 0, 1, 'C')
        self.cell(0, 10, 'January 2026', 0, 1, 'C')

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(26, 26, 46)
        clean_title = self.clean_text(title)
        self.ln(10)
        self.cell(0, 12, clean_title, 0, 1, 'L')
        self.set_draw_color(245, 158, 11)
        self.set_line_width(0.5)
        self.line(self.get_x(), self.get_y(), self.get_x() + 190, self.get_y())
        self.ln(5)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(15, 52, 96)
        self.ln(4)
        self.cell(0, 8, self.clean_text(title), 0, 1, 'L')

    def body_text(self, text, style=''):
        self.set_font('Helvetica', style, 10)
        self.set_text_color(51, 51, 51)
        cleaned = self.clean_text(text)
        self.multi_cell(0, 6, cleaned)
        self.ln(2)

    def draw_table(self, header, data):
        self.set_font('Helvetica', 'B', 10)
        self.set_fill_color(245, 158, 11)
        self.set_text_color(255, 255, 255)
        
        # Calculate column widths
        num_cols = len(header)
        page_width = self.w - 2 * self.l_margin
        col_width = page_width / num_cols
        
        # Header
        for col in header:
            self.cell(col_width, 10, self.clean_text(col), 1, 0, 'C', True)
        self.ln()
        
        # Data
        self.set_font('Helvetica', '', 9)
        self.set_text_color(51, 51, 51)
        for row in data:
            # Calculate max height of the row
            max_h = 10
            for col in row:
                # Approximate line count
                text_len = len(self.clean_text(col))
                lines = (text_len / (col_width / 2.5)) + 1
                max_h = max(max_h, lines * 5)
            
            x = self.get_x()
            y = self.get_y()
            
            for col in row:
                self.multi_cell(col_width, max_h / (max_h/5), self.clean_text(col), 1, 'L')
                self.set_xy(x + col_width, y)
                x += col_width
            self.ln(max_h)

    def clean_text(self, text):
        # Handle common markdown formatting
        text = re.sub(r'\*\*([^*]+)\*\*', r'\1', text)
        text = re.sub(r'__([^_]+)__', r'\1', text)
        text = re.sub(r'`([^`]+)`', r'\1', text)
        # Handle symbols
        replacements = {
            'âœ…': '[OK]',
            'ðŸŽ¯': 'GOAL',
            'ðŸ’Ž': 'VAL',
            'ðŸ“¢': 'CHNL',
            'ðŸ¤ ': 'REL',
            'ðŸ’°': 'REV',
            'ðŸ”‘': 'RES',
            'âš™ï¸ ': 'ACT',
            'ðŸ’¸': 'COST',
            'ðŸ“ˆ': 'STRAT',
            'â­ ': '*',
            'ðŸŸ¢': 'HIGH',
            'ðŸŸ¡': 'MED',
            'â‚¬': 'EUR',
            'orÃ§amento': 'orcamento'
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        # Final cleanup of non-latin
        return text.encode('latin-1', 'replace').decode('latin-1')

def generate():
    with open(md_path, 'r', encoding='utf-8') as f:
        content = f.read()

    pdf = OsterwalderPDF()
    pdf.cover_page()
    pdf.add_page()

    lines = content.split('\n')
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        
        if line.startswith('## '):
            pdf.chapter_title(line[3:])
        elif line.startswith('### '):
            pdf.section_title(line[4:])
        elif line.startswith('> '):
            pdf.set_font('Helvetica', 'I', 10)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 6, pdf.clean_text(line[2:]))
            pdf.ln(2)
        elif line.startswith('|'):
            # Detect table
            header = [c.strip() for c in line.split('|')[1:-1]]
            i += 1 # skip separator line
            i += 1 
            data = []
            while i < len(lines) and lines[i].strip().startswith('|'):
                data.append([c.strip() for c in lines[i].strip().split('|')[1:-1]])
                i += 1
            if header and data:
                pdf.draw_table(header, data)
            continue
        elif line.startswith('- ') or line.startswith('* '):
            pdf.body_text('  • ' + line[2:])
        elif line.strip() and not line.startswith('---'):
            pdf.body_text(line)
        
        i += 1

    pdf.output(pdf_path)
    print(f"Professional PDF created: {pdf_path}")

if __name__ == "__main__":
    generate()
